/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        charcoal: '#565264',
        'dim-grey': '#706677',
        'dusty-mauve': '#A6808C',
        'almond-silk': '#CCB7AE',
        'dust-grey': '#D6CFCB',
        // E-commerce Brand Colors
        'brand-blue': '#0055D4',
        'brand-red': '#DF1E26',
        'brand-yellow': '#FFD000',
        'brand-gray-light': '#F5F5F5',
        // Seller Dashboard specific colors
        "surface-dark": "#1A191E",
        "tertiary": "#493a34",
        "on-secondary-container": "#795763",
        "surface-bright": "#fff8f4",
        "error-container": "#ffdad6",
        "secondary-container": "#fed1de",
        "on-surface": "#1e1b19",
        "surface-variant": "#e8e1dd",
        "surface-container-highest": "#e8e1dd",
        "inverse-on-surface": "#f7efeb",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#484456",
        "surface-dim": "#e0d9d5",
        "on-error": "#ffffff",
        "surface-container-high": "#eee7e3",
        "background": "#fff8f4",
        "secondary-fixed": "#ffd9e4",
        "on-primary-fixed": "#1c1929",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#cac3d9",
        "on-primary-container": "#ccc6dc",
        "secondary": "#775560",
        "on-tertiary-fixed-variant": "#53443d",
        "on-tertiary-fixed": "#251913",
        "on-background": "#1e1b19",
        "tertiary-fixed-dim": "#d8c2b9",
        "electric-blue": "#007AFF",
        "on-surface-variant": "#48464c",
        "primary-fixed": "#e6dff5",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#f5ded4",
        "surface-tint": "#605c6e",
        "surface-container": "#f4ece8",
        "inverse-primary": "#cac3d9",
        "lime-green": "#32D74B",
        "surface-container-low": "#faf2ee",
        "outline-variant": "#c9c5cc",
        "on-secondary-fixed-variant": "#5d3e49",
        "primary-container": "#565264",
        "secondary-fixed-dim": "#e6bbc8",
        "surface": "#fff8f4",
        "on-secondary-fixed": "#2d141d",
        "inverse-surface": "#33302d",
        "primary": "#3f3b4c",
        "on-tertiary-container": "#dac5bc",
        "outline": "#79767c",
        "tertiary-container": "#61514a",
        "on-primary": "#ffffff"
      },
      spacing: {
        "container-max": "1440px",
        "margin-edge": "2rem",
        "gutter": "1.5rem",
        "stack-default": "1.5rem",
        "stack-compact": "0.75rem",
        "sidebar-width": "280px",
        "sidebar-collapsed": "80px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "mono-sm": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
    },
  },
  plugins: [],
};
